apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketblast-api
  template:
    metadata: 
      labels:
        app: ticketblast-api
    spec:
      containers:
      - name: api
        image: ticketblast:v1
        imagePullPolicy: Never # Usa a imagem local que acabamos de buildar
        command: ["node", "dist/server.js"] # Roda a API compilada
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ticketblast-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort # Permite acesso externo
  selector:
    app: ticketblast-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000 # Vamos fixar a porta 30000 para facilitar